#!/bin/bash

CONFIG_PATH=$(pwd)/configuration
SCS_VERSION=2.0.0
# First make sure that the SCS versions used for (1) the Dockerfile and (2)
# this pre-commit hook are in-sync
DOCKERFILE_CONTENTS=$(cat Dockerfile)

if [[ $DOCKERFILE_CONTENTS != *"$SCS_VERSION"* ]]; then
  echo "ERROR: Dockerfile SCS version different from pre-commit hook!"
  exit 1
fi

# Now run the validation script in Docker
docker run --rm -v "$CONFIG_PATH:/etc/scs:ro" "ghcr.io/simple-configuration-server/simple-configuration-server:$SCS_VERSION" python validate.py
