# Simple CI/CD configuration that illustrates how to test the configuration
# data, and build a versioned scs docker image that includes your configuration
# data

# Stages are manually defined, to make sure the testing is done before building
# the image, and not vice-versa
stages:
  - test
  - build
  # In your own implementations, you can also add a deploy stage, to take
  # full advantage of GitLab CI/CD, and automatically deploy if tagged
  # - deploy

validate_configuration:
  stage: test
  image: registry.gitlab.com/tbro/simple-configuration-server:0.12.2
  script:
    - rm -r /etc/scs/*
    - cp -r ./configuration/* /etc/scs
    - cd /app
    - python validate.py
  only:
    - tags
  timeout: 2 minutes

build_docker_image:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - 'if docker pull $IMAGE_TAG > /dev/null 2>&1; then echo "ERROR: An image with the given tag already exists. Please increment the contents of the VERSION file" && exit 1; fi'
    - docker build . -t $IMAGE_TAG
    - docker push $IMAGE_TAG
  only:
    - tags
  timeout: 5 minutes
