validate_configuration:
  stage: test
  image: registry.gitlab.com/tbro/simple-configuration-server:0.12.2
  script:
    - rm -r /etc/scs/*
    - cp -r ./configuration/* /etc/scs
    - cd /app
    - python validate.py

build_docker_image:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - 'if docker pull $IMAGE_TAG > /dev/null 2>&1; then echo "ERROR: An image with the given tag already exists. Please increment the contents of the VERSION file" && exit 1; fi'
    - docker build . -t $IMAGE_TAG
    - docker push $IMAGE_TAG
  only:
    -tags
