# Note that by sending a POST request, the 'heap_size_gb' can also be passed
# in the body as JSON, to override the below value
response:
  headers:
    Content-Type: text/plain

request:
  methods: ["POST"] # Must pass the 'heap_size_gb' property
