# Note that by sending a POST request, the 'heap_size_gb' can also be passed
# in the body as JSON, to override the below value
response:
  headers:
    Content-Type: text/plain

request:
  methods: ["POST"] # Must pass the 'heap_size_gb' property
  # If specific elements should be inside the post request JSON body, add a
  # schema to validate the POST request contents agains
  schema:
    type: object
    required:
      - heap_size_gb
    properties:
      heap_size_gb:
        type: integer
        minimum: 2
        maximum: 32
