# An scs-env.yaml file at the root-level of the config directory, applies to
# all endpoints, unless you override variables in more specific *scs-env.yaml
# files.
template:
  context:
    domain: !scs-common 'remote-files/environments.yaml#staging.domains.[1]'
