template:
  context:
    username: !scs-common 'users/elasticsearch.yaml#[0].username'
    password: !scs-common 'users/elasticsearch.yaml#[0].password'

response:
  headers:
    Content-Type: application/json
