# This is an example of a basic configuration. For all available configuration
# parameters, please refer to configuration/scs-configuration.TEMPLATE.yaml in
# the 'simple-configuration-server' repository
directories:
  common: !scs-expand-env ${SCS_CONFIG_DIR}/common
  config: !scs-expand-env ${SCS_CONFIG_DIR}/config
  secrets: &secrets-dir !scs-expand-env ${SCS_CONFIG_DIR}/secrets

logs:
  audit:
    file:
      path: /var/log/scs/audit.log.jsonl
      max_size_mb: 1
      backup_count: 5
      level: INFO
  application:
    file:
      path: /var/log/scs/app.log.jsonl
      max_size_mb: 1
      backup_count: 5
      level: INFO

auth:
  options:
    users_file: !scs-expand-env ${SCS_CONFIG_DIR}/scs-users.yaml
    directories:
      secrets: *secrets-dir
    networks:
      private_only: true
      whitelist:
      # These example values are configured to match the ranges used by Docker
      # so this example server can be accessed from localhost when running
      # locally. Note that this also whitelists the 192.168 range, which means
      # it may be accessible from your local-network if you use this range, and
      # do not have a Firewall in-place.
      # For production deployments, ALWAYS restrict these values to only the
      # ranges that need access. You can add individual IP addresses to the
      # list, or use the CIDR notation to whitelist complete networks.
      - 172.16.0.0/12
      - 192.168.0.0/16
    max_auth_fails_per_15_min: 10
